// generatePDF.ts
// Client-side PDF generation for iGITit using jsPDF
// Dynamically loads jsPDF from CDN — no install needed

declare global {
  interface Window { jspdf: { jsPDF: new (opts?: object) => jsPDFInstance } }
}

interface jsPDFInstance {
  setFontSize(size: number): void
  setFont(name: string, style?: string): void
  setTextColor(r: number, g?: number, b?: number): void
  setFillColor(r: number, g?: number, b?: number): void
  setDrawColor(r: number, g?: number, b?: number): void
  setLineWidth(w: number): void
  rect(x: number, y: number, w: number, h: number, style?: string): void
  text(text: string | string[], x: number, y: number, opts?: object): void
  line(x1: number, y1: number, x2: number, y2: number): void
  addPage(): void
  save(filename: string): void
  internal: { pageSize: { getWidth(): number; getHeight(): number } }
  splitTextToSize(text: string, maxWidth: number): string[]
  getTextWidth(text: string): number
  circle(x: number, y: number, r: number, style?: string): void
}

async function loadJsPDF(): Promise<typeof window.jspdf.jsPDF> {
  if (window.jspdf?.jsPDF) return window.jspdf.jsPDF
  await new Promise<void>((resolve, reject) => {
    const script = document.createElement("script")
    script.src = "https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js"
    script.onload = () => resolve()
    script.onerror = () => reject(new Error("Failed to load jsPDF"))
    document.head.appendChild(script)
  })
  return window.jspdf.jsPDF
}

// ── Color constants ──────────────────────────────────────
const C = {
  black:    [11, 11, 12] as [number,number,number],
  white:    [255, 255, 255] as [number,number,number],
  blue:     [74, 158, 240] as [number,number,number],
  green:    [76, 175, 125] as [number,number,number],
  red:      [224, 92, 92] as [number,number,number],
  text:     [26, 26, 26] as [number,number,number],
  muted:    [100, 100, 100] as [number,number,number],
  light:    [248, 248, 246] as [number,number,number],
  border:   [232, 232, 228] as [number,number,number],
  subtext:  [68, 68, 68] as [number,number,number],
}

// ── Drawing helpers ──────────────────────────────────────
function makeHelpers(doc: jsPDFInstance) {
  const W = doc.internal.pageSize.getWidth()

  function header(repoLabel: string, date: string, subtitle?: string) {
    // Dark header bar
    doc.setFillColor(...C.black)
    doc.rect(0, 0, W, 44, "F")
    // Logo
    doc.setFontSize(18)
    doc.setFont("courier", "bold")
    doc.setTextColor(...C.white)
    doc.text("iGITit", 14, 28)
    // Blue dot above logo
    doc.setFillColor(...C.blue)
    doc.circle(14, 8, 2.5, "F")
    // Tagline
    doc.setFontSize(8)
    doc.setFont("courier", "normal")
    doc.setTextColor(150, 150, 150)
    doc.text("open source, open language.", 14, 38)
    // Right side
    doc.setFontSize(8)
    doc.setTextColor(160, 160, 160)
    doc.text("ANALYSIS REPORT", W - 14, 18, { align: "right" })
    doc.setTextColor(120, 120, 120)
    doc.text(date, W - 14, 26, { align: "right" })
    doc.text("generated by iGITit · OMARO PBC", W - 14, 34, { align: "right" })
  }

  function repoBar(y: number, name: string, desc: string, pills: string[]) {
    doc.setFillColor(...C.light)
    doc.rect(0, y, W, 22, "F")
    doc.setDrawColor(...C.border)
    doc.setLineWidth(0.1)
    doc.line(0, y, W, y)
    doc.line(0, y + 22, W, y + 22)
    doc.setFontSize(12)
    doc.setFont("courier", "bold")
    doc.setTextColor(...C.text)
    doc.text(name, 14, y + 9)
    doc.setFontSize(8)
    doc.setFont("courier", "normal")
    doc.setTextColor(...C.muted)
    doc.text(desc.slice(0, 80), 14, y + 17)
    // Pills
    let px = W - 14
    pills.slice().reverse().forEach(pill => {
      const pw = doc.getTextWidth(pill) + 8
      px -= pw
      doc.setFillColor(...C.white)
      doc.setDrawColor(...C.border)
      doc.rect(px, y + 5, pw, 10, "FD")
      doc.setFontSize(7)
      doc.setTextColor(...C.muted)
      doc.text(pill, px + 4, y + 12)
      px -= 4
    })
  }

  function sectionLabel(y: number, label: string) {
    doc.setFontSize(7)
    doc.setFont("courier", "normal")
    doc.setTextColor(...C.muted)
    doc.text(label, 14, y)
    doc.setDrawColor(...C.border)
    doc.setLineWidth(0.1)
    doc.line(14, y + 2, W - 14, y + 2)
  }

  function sectionTitle(y: number, title: string) {
    doc.setFontSize(10)
    doc.setFont("courier", "bold")
    doc.setTextColor(...C.text)
    doc.text(title, 14, y)
  }

  function bodyText(x: number, y: number, text: string, maxW: number): number {
    doc.setFontSize(9)
    doc.setFont("courier", "normal")
    doc.setTextColor(...C.subtext)
    const lines = doc.splitTextToSize(text, maxW)
    doc.text(lines, x, y)
    return lines.length * 5
  }

  function scoreRow(y: number, label: string, pct: number, verdict: string, pass: boolean) {
    doc.setFontSize(8)
    doc.setFont("courier", "normal")
    doc.setTextColor(...C.subtext)
    doc.text(label, 14, y)
    // Bar track
    doc.setFillColor(...C.border)
    doc.rect(100, y - 4, 80, 3, "F")
    // Bar fill
    doc.setFillColor(...(pass ? C.green : C.red))
    doc.rect(100, y - 4, 80 * (pct / 100), 3, "F")
    // Verdict
    doc.setTextColor(...(pass ? C.green : C.red))
    doc.text(verdict, W - 14, y, { align: "right" })
  }

  function divider(y: number) {
    doc.setDrawColor(...C.border)
    doc.setLineWidth(0.1)
    doc.line(14, y, W - 14, y)
  }

  function footer() {
    const H = doc.internal.pageSize.getHeight()
    doc.setFillColor(...C.light)
    doc.rect(0, H - 14, W, 14, "F")
    doc.setDrawColor(...C.border)
    doc.setLineWidth(0.1)
    doc.line(0, H - 14, W, H - 14)
    doc.setFontSize(6.5)
    doc.setFont("courier", "normal")
    doc.setTextColor(...C.muted)
    doc.text("generated by iGITit · powered by Claude · an OMARO PBC product · not legal or compliance advice", 14, H - 6)
    doc.setTextColor(...C.blue)
    doc.text("igitit.xyz", W - 14, H - 6, { align: "right" })
  }

  function checkPage(doc: jsPDFInstance, y: number, needed = 20): number {
    const H = doc.internal.pageSize.getHeight()
    if (y + needed > H - 20) {
      doc.addPage()
      footer()
      return 20
    }
    return y
  }

  return { header, repoBar, sectionLabel, sectionTitle, bodyText, scoreRow, divider, footer, checkPage, W }
}

// ── Main export: single repo ─────────────────────────────
export async function downloadAnalysisPDF(
  analysis: Record<string, unknown>,
  meta: Record<string, unknown>,
  changelog?: Record<string, unknown>[],
) {
  const jsPDF = await loadJsPDF()
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" })
  const h = makeHelpers(doc)
  const date = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })
  const repoName = `${meta.owner ?? ""}/${meta.repo ?? ""}`
  const desc = (meta.description as string) ?? ""
  const pills = [
    (meta.platform as string) ?? "GitHub",
    (meta.language as string) ?? "Unknown",
    meta.stars ? `★ ${Number(meta.stars).toLocaleString()}` : "",
    (meta.license as string) ?? "",
  ].filter(Boolean)

  // PAGE 1 ─────────────────────────────────────────────
  h.header(repoName, date)
  h.repoBar(44, repoName, desc, pills)
  h.footer()

  let y = 78

  // OVERVIEW
  h.sectionLabel(y, "OVERVIEW"); y += 8
  const overview = analysis.overview as Record<string, string> ?? {}
  const overviewFields = [
    { title: "What this software does", key: "purpose" },
    { title: "Who builds it", key: "ownership" },
    { title: "Who uses it", key: "userBase" },
    { title: "License & usage rights", key: "license" },
    { title: "Notable concerns", key: "concerns" },
  ]
  for (const field of overviewFields) {
    const text = overview[field.key] ?? ""
    if (!text) continue
    y = h.checkPage(doc, y, 20)
    h.sectionTitle(y, field.title); y += 6
    y += h.bodyText(14, y, text, h.W - 28); y += 6
  }

  h.divider(y); y += 8

  // DATA NARRATIVE
  y = h.checkPage(doc, y, 20)
  h.sectionLabel(y, "DATA NARRATIVE"); y += 8
  const dataNarrative = analysis.dataNarrative as Record<string, unknown>[] ?? []
  for (const item of dataNarrative) {
    y = h.checkPage(doc, y, 14)
    const typeColor = item.type === "collected" ? C.blue : item.type === "stored" ? C.green : C.red
    doc.setFillColor(...typeColor)
    doc.circle(17, y - 1.5, 2, "F")
    doc.setFontSize(9)
    doc.setFont("courier", "bold")
    doc.setTextColor(...C.text)
    doc.text(String(item.name ?? ""), 22, y)
    doc.setFont("courier", "normal")
    doc.setTextColor(...C.subtext)
    const desc2 = String(item.description ?? "")
    const lines = doc.splitTextToSize(desc2, h.W - 36)
    if (lines.length > 0) {
      doc.setFontSize(8)
      doc.text(lines[0], 22, y + 5)
      if (lines.length > 1) {
        y += h.bodyText(22, y + 10, lines.slice(1).join(" "), h.W - 36)
      }
    }
    y += 12
  }

  h.divider(y); y += 8

  // ACCOUNTABILITY SCORE
  y = h.checkPage(doc, y, 20)
  h.sectionLabel(y, "ACCOUNTABILITY SCORE"); y += 8
  const score = analysis.score as Record<string, unknown> ?? {}
  const dimensions = score.dimensions as Record<string, unknown>[] ?? []
  for (const dim of dimensions) {
    y = h.checkPage(doc, y, 10)
    const pass = dim.pass as boolean
    const pct = pass ? 85 : 20
    h.scoreRow(y, String(dim.label ?? dim.name ?? ""), pct, String(dim.verdict ?? (pass ? "pass" : "fail")), pass)
    y += 8
  }

  h.divider(y); y += 8

  // OVERALL VERDICT
  y = h.checkPage(doc, y, 30)
  h.sectionLabel(y, "OVERALL VERDICT"); y += 8
  const verdictText = String((score.verdict as string) ?? (analysis.verdict as string) ?? "")
  if (verdictText) {
    doc.setFillColor(...C.light)
    const lines = doc.splitTextToSize(verdictText, h.W - 42)
    const boxH = lines.length * 5 + 10
    doc.rect(14, y - 2, h.W - 28, boxH, "F")
    doc.setFontSize(9)
    doc.setFont("courier", "normal")
    doc.setTextColor(...C.subtext)
    doc.text(lines, 20, y + 5)
    y += boxH + 8
  }

  // MODULE BREAKDOWN
  const modules = analysis.modules as Record<string, unknown>[] ?? []
  if (modules.length > 0) {
    doc.addPage()
    h.header(repoName, date)
    h.footer()
    y = 58
    h.sectionLabel(y, "MODULE BREAKDOWN"); y += 8
    for (const mod of modules) {
      y = h.checkPage(doc, y, 24)
      h.sectionTitle(y, String(mod.name ?? mod.path ?? "")); y += 6
      const modDesc = String(mod.description ?? "")
      if (modDesc) { y += h.bodyText(14, y, modDesc, h.W - 28); y += 4 }
      const purpose = String(mod.purpose ?? "")
      if (purpose) {
        doc.setFontSize(8)
        doc.setTextColor(...C.muted)
        doc.setFont("courier", "normal")
        doc.text(`purpose: ${purpose}`, 14, y); y += 5
      }
      h.divider(y); y += 6
    }
  }

  // CHANGELOG
  if (changelog && changelog.length > 0) {
    doc.addPage()
    h.header(repoName, date)
    h.footer()
    y = 58
    h.sectionLabel(y, "CHANGE LOG"); y += 8
    for (const commit of changelog.slice(0, 30)) {
      y = h.checkPage(doc, y, 18)
      const sig = String(commit.significance ?? "routine")
      const sigColor = sig === "flagged" ? C.red : sig === "notable" ? [186, 117, 23] as [number,number,number] : C.muted
      doc.setFillColor(...sigColor)
      doc.circle(17, y - 1.5, 2, "F")
      doc.setFontSize(8)
      doc.setFont("courier", "bold")
      doc.setTextColor(...C.text)
      doc.text(String(commit.sha ?? "").slice(0, 7), 22, y)
      doc.setFont("courier", "normal")
      doc.setTextColor(...C.subtext)
      const summary = String(commit.message ?? commit.summary ?? "")
      const lines = doc.splitTextToSize(summary, h.W - 50)
      doc.text(lines[0] ?? "", 40, y)
      if (lines.length > 1) {
        doc.setFontSize(7.5)
        doc.text(lines.slice(1).join(" "), 22, y + 5)
        y += 5
      }
      if (commit.plainLanguage) {
        doc.setFontSize(7.5)
        doc.setTextColor(...C.muted)
        doc.text(`→ ${String(commit.plainLanguage).slice(0, 90)}`, 22, y + 5)
        y += 5
      }
      y += 10
    }
  }

  doc.save(`igitit-${String(meta.repo ?? "report")}-${Date.now()}.pdf`)
}

// ── Compare report ───────────────────────────────────────
export async function downloadComparePDF(
  analysisA: Record<string, unknown>,
  metaA: Record<string, unknown>,
  analysisB: Record<string, unknown>,
  metaB: Record<string, unknown>,
  comparison: Record<string, unknown>,
) {
  const jsPDF = await loadJsPDF()
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" })
  const h = makeHelpers(doc)
  const date = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })
  const nameA = `${metaA.owner ?? ""}/${metaA.repo ?? ""}`
  const nameB = `${metaB.owner ?? ""}/${metaB.repo ?? ""}`
  h.footer()

  // COVER
  doc.setFillColor(...C.black)
  doc.rect(0, 0, h.W, 44, "F")
  doc.setFontSize(18)
  doc.setFont("courier", "bold")
  doc.setTextColor(...C.white)
  doc.text("iGITit", 14, 28)
  doc.setFillColor(...C.blue)
  doc.circle(14, 8, 2.5, "F")
  doc.setFontSize(8)
  doc.setFont("courier", "normal")
  doc.setTextColor(150, 150, 150)
  doc.text("open source, open language.", 14, 38)
  doc.setFontSize(8)
  doc.setTextColor(160, 160, 160)
  doc.text("COMPARISON REPORT", h.W - 14, 18, { align: "right" })
  doc.text(date, h.W - 14, 26, { align: "right" })
  doc.text("generated by iGITit · OMARO PBC", h.W - 14, 34, { align: "right" })

  // Repo bars side by side
  const colW = (h.W - 28) / 2
  // Repo A
  doc.setFillColor(...C.light)
  doc.rect(0, 44, h.W / 2, 22, "F")
  doc.setDrawColor(...C.border)
  doc.setLineWidth(0.1)
  doc.line(0, 44, h.W / 2, 44)
  doc.line(0, 66, h.W / 2, 66)
  doc.setFontSize(9)
  doc.setFont("courier", "bold")
  doc.setTextColor(...C.text)
  doc.text(nameA, 14, 54)
  doc.setFontSize(7)
  doc.setFont("courier", "normal")
  doc.setTextColor(...C.muted)
  doc.text(String(metaA.description ?? "").slice(0, 45), 14, 62)
  // Repo B
  doc.setFillColor(...C.light)
  doc.rect(h.W / 2, 44, h.W / 2, 22, "F")
  doc.line(h.W / 2, 44, h.W, 44)
  doc.line(h.W / 2, 66, h.W, 66)
  doc.setFontSize(9)
  doc.setFont("courier", "bold")
  doc.setTextColor(...C.text)
  doc.text(nameB, h.W / 2 + 4, 54)
  doc.setFontSize(7)
  doc.setFont("courier", "normal")
  doc.setTextColor(...C.muted)
  doc.text(String(metaB.description ?? "").slice(0, 45), h.W / 2 + 4, 62)

  let y = 78

  // Comparison sections
  const sections = comparison.sections as Record<string, unknown>[] ?? []
  for (const section of sections) {
    y = h.checkPage(doc, y, 30)
    h.sectionLabel(y, String(section.label ?? section.title ?? "").toUpperCase()); y += 8
    // Side by side
    const textA = String(section.repoA ?? section.a ?? "")
    const textB = String(section.repoB ?? section.b ?? "")
    const linesA = doc.splitTextToSize(textA, colW - 4)
    const linesB = doc.splitTextToSize(textB, colW - 4)
    doc.setFontSize(8)
    doc.setFont("courier", "normal")
    doc.setTextColor(...C.subtext)
    doc.text(linesA, 14, y)
    doc.text(linesB, h.W / 2 + 4, y)
    const rowH = Math.max(linesA.length, linesB.length) * 4.5 + 4
    doc.setDrawColor(...C.border)
    doc.setLineWidth(0.1)
    doc.line(h.W / 2, y - 4, h.W / 2, y + rowH)
    y += rowH + 4
    h.divider(y); y += 8
  }

  // Key differences
  const diffs = comparison.keyDifferences as string[] ?? []
  if (diffs.length > 0) {
    y = h.checkPage(doc, y, 20)
    h.sectionLabel(y, "KEY DIFFERENCES"); y += 8
    for (const diff of diffs) {
      y = h.checkPage(doc, y, 10)
      doc.setFillColor(...C.blue)
      doc.circle(17, y - 1.5, 1.5, "F")
      const lines = doc.splitTextToSize(diff, h.W - 36)
      doc.setFontSize(8)
      doc.setFont("courier", "normal")
      doc.setTextColor(...C.subtext)
      doc.text(lines, 22, y)
      y += lines.length * 4.5 + 4
    }
    h.divider(y); y += 8
  }

  // Overall winner
  const winner = String(comparison.winner ?? comparison.verdict ?? "")
  if (winner) {
    y = h.checkPage(doc, y, 30)
    h.sectionLabel(y, "OVERALL VERDICT"); y += 8
    const lines = doc.splitTextToSize(winner, h.W - 42)
    const boxH = lines.length * 5 + 10
    doc.setFillColor(...C.light)
    doc.rect(14, y - 2, h.W - 28, boxH, "F")
    doc.setFontSize(9)
    doc.setFont("courier", "normal")
    doc.setTextColor(...C.subtext)
    doc.text(lines, 20, y + 5)
    y += boxH + 8
  }

  // For journalists
  const forJ = String(comparison.forJournalists ?? comparison.journalistNote ?? "")
  if (forJ) {
    y = h.checkPage(doc, y, 20)
    h.sectionLabel(y, "FOR JOURNALISTS"); y += 8
    h.bodyText(14, y, forJ, h.W - 28)
  }

  doc.save(`igitit-compare-${String(metaA.repo ?? "a")}-vs-${String(metaB.repo ?? "b")}-${Date.now()}.pdf`)
}
