// generatePDF.ts — iGITit client-side PDF generation via jsPDF

declare global {
  interface Window { jspdf: { jsPDF: new (opts?: object) => JPDF } }
}

interface JPDF {
  setFontSize(s: number): void
  setFont(n: string, style?: string): void
  setTextColor(r: number, g?: number, b?: number): void
  setFillColor(r: number, g?: number, b?: number): void
  setDrawColor(r: number, g?: number, b?: number): void
  setLineWidth(w: number): void
  rect(x: number, y: number, w: number, h: number, s?: string): void
  text(t: string | string[], x: number, y: number, o?: object): void
  line(x1: number, y1: number, x2: number, y2: number): void
  addPage(): void
  save(f: string): void
  internal: { pageSize: { getWidth(): number; getHeight(): number } }
  splitTextToSize(t: string, w: number): string[]
  getTextWidth(t: string): number
  circle(x: number, y: number, r: number, s?: string): void
}

async function loadJsPDF(): Promise<new (o?: object) => JPDF> {
  if (window.jspdf?.jsPDF) return window.jspdf.jsPDF
  await new Promise<void>((res, rej) => {
    const s = document.createElement("script")
    s.src = "https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js"
    s.onload = () => res()
    s.onerror = () => rej(new Error("jsPDF load failed"))
    document.head.appendChild(s)
  })
  return window.jspdf.jsPDF
}

const C = {
  black:   [11,11,12] as [number,number,number],
  white:   [255,255,255] as [number,number,number],
  blue:    [74,158,240] as [number,number,number],
  green:   [76,175,125] as [number,number,number],
  red:     [224,92,92] as [number,number,number],
  amber:   [186,117,23] as [number,number,number],
  text:    [26,26,26] as [number,number,number],
  muted:   [120,120,120] as [number,number,number],
  subtext: [68,68,68] as [number,number,number],
  light:   [248,248,246] as [number,number,number],
  border:  [232,232,228] as [number,number,number],
}

// A4 = 210mm wide. Safe text area: x=14 to x=196 = 182mm usable.
// Verdict box inner text: x=18 to x=192 = 174mm — use 170mm for splitTextToSize to be safe.

function helpers(doc: JPDF) {
  const W = doc.internal.pageSize.getWidth()   // 210mm
  const H = doc.internal.pageSize.getHeight()  // 297mm
  const TEXT_W = W - 28    // 182mm — full page text width
  const INNER_W = W - 40 - 6  // 164mm — inside padded boxes (accounts for x=20 text start)

  // Header with dot flush left of "iGITit"
  const header = (date: string, reportType: string, verified?: boolean, cid?: string) => {
    doc.setFillColor(...C.black); doc.rect(0,0,W,46,"F")
    // Blue dot at same y baseline as iGITit text, flush left
    doc.setFillColor(...C.blue); doc.circle(17,22,3,"F")
    // iGITit immediately after dot
    doc.setFontSize(20); doc.setFont("courier","bold"); doc.setTextColor(...C.white)
    doc.text("iGITit",23,27)
    // Tagline directly below
    doc.setFontSize(8); doc.setFont("courier","normal"); doc.setTextColor(140,140,140)
    doc.text("open source, open language.",23,36)
    // Right side metadata
    doc.setFontSize(8); doc.setTextColor(160,160,160)
    doc.text(reportType.toUpperCase(),W-14,16,{align:"right"})
    doc.text(date,W-14,24,{align:"right"})
    doc.text("generated by iGITit · OMARO PBC",W-14,32,{align:"right"})
    // Verified badge if present
    if (verified && cid) {
      doc.setFontSize(7); doc.setTextColor(...C.green)
      doc.text(`verified · pinned to IPFS · ${cid.slice(0,20)}...`,W-14,40,{align:"right"})
    }
  }

  const repoBar = (name: string, desc: string, pills: string[]) => {
    const barY = 46
    doc.setFillColor(...C.light); doc.rect(0,barY,W,22,"F")
    doc.setDrawColor(...C.border); doc.setLineWidth(0.1)
    doc.line(0,barY,W,barY); doc.line(0,barY+22,W,barY+22)
    doc.setFontSize(11); doc.setFont("courier","bold"); doc.setTextColor(...C.text)
    doc.text(name,14,barY+9)
    doc.setFontSize(8); doc.setFont("courier","normal"); doc.setTextColor(...C.muted)
    if (desc) doc.text(desc.slice(0,90),14,barY+17)
    // Pills right-aligned
    let px = W-14
    pills.slice().reverse().forEach(pill => {
      const pw = doc.getTextWidth(pill)+8; px -= pw
      doc.setFillColor(...C.white); doc.setDrawColor(...C.border)
      doc.rect(px,barY+6,pw,9,"FD")
      doc.setFontSize(7); doc.setTextColor(...C.muted)
      doc.text(pill,px+4,barY+12); px -= 3
    })
  }

  const footer = () => {
    doc.setFillColor(...C.light); doc.rect(0,H-12,W,12,"F")
    doc.setDrawColor(...C.border); doc.setLineWidth(0.1); doc.line(0,H-12,W,H-12)
    doc.setFontSize(6.5); doc.setFont("courier","normal"); doc.setTextColor(...C.muted)
    doc.text("generated by iGITit · powered by Claude · an OMARO PBC product · not legal or compliance advice",14,H-5)
    doc.setTextColor(...C.blue); doc.text("igitit.xyz",W-14,H-5,{align:"right"})
  }

  const sectionLabel = (y: number, label: string) => {
    doc.setFontSize(7); doc.setFont("courier","normal"); doc.setTextColor(...C.muted)
    doc.text(label,14,y)
    doc.setDrawColor(...C.border); doc.setLineWidth(0.1); doc.line(14,y+2,W-14,y+2)
  }

  const sectionTitle = (y: number, title: string) => {
    doc.setFontSize(10); doc.setFont("courier","bold"); doc.setTextColor(...C.text)
    doc.text(title,14,y)
  }

  const bodyText = (x: number, y: number, text: string, maxW: number): number => {
    doc.setFontSize(9); doc.setFont("courier","normal"); doc.setTextColor(...C.subtext)
    const lines = doc.splitTextToSize(text, maxW)
    doc.text(lines,x,y)
    return lines.length * 5
  }

  const divider = (y: number) => {
    doc.setDrawColor(...C.border); doc.setLineWidth(0.1); doc.line(14,y,W-14,y)
  }

  const verdictBox = (y: number, text: string): number => {
    // courier is very wide — use 130mm to guarantee no overflow
    const lines = doc.splitTextToSize(text, 130)
    const boxH = lines.length * 5.2 + 14
    doc.setFillColor(...C.light)
    doc.rect(14, y, W-28, boxH, "F")
    doc.setDrawColor(...C.border); doc.setLineWidth(0.1)
    doc.rect(14, y, W-28, boxH, "D")
    doc.setFontSize(8.5); doc.setFont("courier","normal"); doc.setTextColor(...C.subtext)
    doc.text(lines, 20, y+8)
    return boxH
  }

  const checkPage = (y: number, needed = 20): number => {
    if (y + needed > H - 18) { doc.addPage(); footer(); return 20 }
    return y
  }

  return { header, repoBar, footer, sectionLabel, sectionTitle, bodyText, divider, verdictBox, checkPage, W, H, TEXT_W, INNER_W }
}

// ── Exported types matching page.tsx exactly ─────────────
export interface OverviewSection { title: string; content: string }
export interface DataItem { type: "collect"|"store"|"send"; label: string; description: string; sourceLine?: string }
export interface Module { name: string; path: string; description: string; sourceSnippet?: string }
export interface RescuePillar { score: number; finding: string }
export interface RescueScore { R: RescuePillar; E: RescuePillar; S: RescuePillar; C: RescuePillar; U: RescuePillar; E2: RescuePillar; A: RescuePillar; I: RescuePillar }
export interface Analysis {
  meta?: Record<string,unknown>
  overview: OverviewSection[]
  dataItems: DataItem[]
  dataFlowSummary: string
  modules: Module[]
  rescue: RescueScore
  overallVerdict: string
}
export interface ChangelogEntry {
  sha: string; date: string; author: string
  originalMessage: string; plainTitle: string; plainSummary: string
  significance: "routine"|"notable"|"flagged"
  significanceReason: string; affectedAreas: string[]
}
export interface RepoMeta {
  owner: string; repo: string; description: string; language: string
  stars: number; topics: string[]; license: string|null; updatedAt: string|null; platform?: string
}
export interface CompareSection {
  title: string; leftSummary: string; rightSummary: string; verdict: string
}
export interface Comparison {
  headline: string
  sections: CompareSection[]
  overallWinner: { label: string; repoName: string; reasoning: string }
  keyDifferences: string[]
  forJournalists: string
}

// ── Single repo PDF ───────────────────────────────────────
export async function downloadAnalysisPDF(
  analysis: Analysis,
  meta: RepoMeta,
  changelog?: ChangelogEntry[],
  verified?: boolean,
  cid?: string,
) {
  const jsPDF = await loadJsPDF()
  const doc = new jsPDF({ orientation:"portrait", unit:"mm", format:"a4" })
  const h = helpers(doc)
  const date = new Date().toLocaleDateString("en-US",{year:"numeric",month:"long",day:"numeric"})
  const repoName = `${meta.owner}/${meta.repo}`
  const pills = [
    meta.platform ?? "GitHub",
    meta.language ?? "Unknown",
    meta.stars ? `${meta.stars.toLocaleString()} stars` : "",
    meta.license ?? "",
  ].filter(Boolean)

  h.header(date, "Analysis Report", verified, cid)
  h.repoBar(repoName, meta.description ?? "", pills)
  h.footer()

  let y = 78

  // ── OVERVIEW ──────────────────────────────────────────
  h.sectionLabel(y, "OVERVIEW"); y += 8
  for (const section of analysis.overview ?? []) {
    y = h.checkPage(y, 22)
    h.sectionTitle(y, section.title.toUpperCase()); y += 6
    y += h.bodyText(14, y, section.content, h.TEXT_W); y += 5
  }
  h.divider(y); y += 7

  // ── DATA NARRATIVE ────────────────────────────────────
  y = h.checkPage(y, 20)
  h.sectionLabel(y, "DATA NARRATIVE"); y += 8

  for (const item of analysis.dataItems ?? []) {
    y = h.checkPage(y, 16)
    const dotColor = item.type === "collect" ? C.blue : item.type === "store" ? C.green : C.red
    doc.setFillColor(...dotColor); doc.circle(17, y-1.5, 2, "F")
    doc.setFontSize(9); doc.setFont("courier","bold"); doc.setTextColor(...C.text)
    doc.text(item.label, 22, y)
    const descLines = doc.splitTextToSize(item.description, h.TEXT_W - 10)
    doc.setFontSize(8); doc.setFont("courier","normal"); doc.setTextColor(...C.subtext)
    doc.text(descLines, 22, y+5)
    y += 5 + descLines.length * 4.5 + 3
  }

  if (analysis.dataFlowSummary) {
    y = h.checkPage(y, 16)
    const sumLines = doc.splitTextToSize(analysis.dataFlowSummary, h.TEXT_W)
    doc.setFontSize(8); doc.setFont("courier","normal"); doc.setTextColor(...C.muted)
    doc.text(sumLines, 14, y)
    y += sumLines.length * 4.5 + 4
  }

  // Legend — tight, no extra gap
  const legendItems = [
    { color: C.blue, label: "collected" },
    { color: C.green, label: "stored" },
    { color: C.red, label: "transmitted" },
  ]
  let lx = 14
  for (const li of legendItems) {
    doc.setFillColor(...li.color); doc.circle(lx+2, y-1.5, 1.5, "F")
    doc.setFontSize(7); doc.setFont("courier","normal"); doc.setTextColor(...C.muted)
    doc.text(li.label, lx+6, y)
    lx += doc.getTextWidth(li.label) + 14
  }
  y += 5
  h.divider(y); y += 7

  // ── RESCUE SCORE ─────────────────────────────────────
  y = h.checkPage(y, 20)
  const rescuePillars = [
    { key: "R", label: "Resilience & Dependency Prevention" },
    { key: "E", label: "Equality / Non-Discrimination" },
    { key: "S", label: "Safety & Robustness" },
    { key: "C", label: "Control & Human Oversight" },
    { key: "U", label: "Use Limits & Proportionality" },
    { key: "E2", label: "Empowerment & Rights" },
    { key: "A", label: "Accountability & Privacy" },
    { key: "I", label: "Integrity & Transparency" },
  ]
  const rScore = analysis.rescue
  const totalRaw = rScore ? Object.values(rScore).reduce((s, p) => s + (p as RescuePillar).score, 0) : 0
  const grade = totalRaw >= 36 ? "A" : totalRaw >= 30 ? "B" : totalRaw >= 24 ? "C" : totalRaw >= 16 ? "D" : "F"
  h.sectionLabel(y, `RESCUE SCORE · [${grade}] ${totalRaw}/40 · GOVERNED BY OMARO PBC`); y += 8
  if (rScore) {
    for (const { key, label } of rescuePillars) {
      y = h.checkPage(y, 12)
      const pillar = rScore[key as keyof RescueScore]
      const pct = (pillar.score / 5) * 55
      const col = pillar.score >= 4 ? C.green : pillar.score >= 3 ? C.blue : pillar.score >= 2 ? C.amber : C.red
      doc.setFontSize(8); doc.setFont("courier","normal"); doc.setTextColor(...C.subtext)
      doc.text(`[${key}] ${label}`, 14, y)
      doc.setFillColor(...C.border); doc.rect(100, y-4, 55, 3, "F")
      doc.setFillColor(...col); doc.rect(100, y-4, pct, 3, "F")
      doc.setFontSize(8); doc.setTextColor(...col)
      doc.text(`${pillar.score}/5`, h.W-14, y, {align:"right"})
      const findLines = doc.splitTextToSize(pillar.finding, h.TEXT_W - 10)
      doc.setFontSize(7); doc.setTextColor(...C.muted)
      doc.text(findLines[0], 14, y+4)
      y += 12
    }
  }
  h.divider(y); y += 7

  // ── OVERALL VERDICT ───────────────────────────────────
  y = h.checkPage(y, 35)
  h.sectionLabel(y, "OVERALL VERDICT"); y += 8
  if (analysis.overallVerdict) {
    const boxH = h.verdictBox(y, analysis.overallVerdict)
    y += boxH + 8
  }

  // ── MODULE BREAKDOWN ──────────────────────────────────
  if (analysis.modules?.length > 0) {
    doc.addPage(); h.header(date, "Analysis Report", verified, cid); h.footer()
    y = 56
    h.sectionLabel(y, "MODULE BREAKDOWN"); y += 8
    for (const mod of analysis.modules) {
      y = h.checkPage(y, 24)
      h.sectionTitle(y, `${mod.name}  ·  ${mod.path}`); y += 6
      y += h.bodyText(14, y, mod.description, h.TEXT_W); y += 3
      h.divider(y); y += 7
    }
  }

  // ── CHANGELOG ─────────────────────────────────────────
  if (changelog && changelog.length > 0) {
    doc.addPage(); h.header(date, "Analysis Report", verified, cid); h.footer()
    y = 56
    h.sectionLabel(y, `CHANGE LOG  (${Math.min(changelog.length,50)} commits)`); y += 8
    for (const commit of changelog.slice(0,50)) {
      y = h.checkPage(y, 18)
      const sigColor = commit.significance === "flagged" ? C.red : commit.significance === "notable" ? C.amber : C.muted
      doc.setFillColor(...sigColor); doc.circle(17, y-1.5, 2, "F")
      doc.setFontSize(8); doc.setFont("courier","bold"); doc.setTextColor(...C.text)
      doc.text(commit.sha.slice(0,7), 22, y)
      doc.setFont("courier","normal"); doc.setTextColor(...C.subtext)
      const titleLines = doc.splitTextToSize(commit.plainTitle ?? commit.originalMessage ?? "", h.TEXT_W - 20)
      doc.text(titleLines[0] ?? "", 40, y)
      if (commit.plainSummary) {
        doc.setFontSize(7.5); doc.setTextColor(...C.muted)
        const sumLines = doc.splitTextToSize(`  ${commit.plainSummary}`, h.TEXT_W - 14)
        doc.text(sumLines[0], 22, y+5)
        y += 5
      }
      y += 9
    }
  }

  doc.save(`igitit-${meta.repo}-${Date.now()}.pdf`)
}

// ── Compare PDF ───────────────────────────────────────────
export async function downloadComparePDF(
  analysisA: Analysis,
  metaA: RepoMeta,
  analysisB: Analysis,
  metaB: RepoMeta,
  comparison: Comparison,
) {
  const jsPDF = await loadJsPDF()
  const doc = new jsPDF({ orientation:"portrait", unit:"mm", format:"a4" })
  const h = helpers(doc)
  const date = new Date().toLocaleDateString("en-US",{year:"numeric",month:"long",day:"numeric"})
  const nameA = `${metaA.owner}/${metaA.repo}`
  const nameB = `${metaB.owner}/${metaB.repo}`
  const colW = (h.W - 40) / 2

  h.footer()

  // Header
  doc.setFillColor(...C.black); doc.rect(0,0,h.W,46,"F")
  doc.setFillColor(...C.blue); doc.circle(17,22,3,"F")
  doc.setFontSize(20); doc.setFont("courier","bold"); doc.setTextColor(...C.white)
  doc.text("iGITit",23,27)
  doc.setFontSize(8); doc.setFont("courier","normal"); doc.setTextColor(140,140,140)
  doc.text("open source, open language.",23,36)
  doc.setFontSize(8); doc.setTextColor(160,160,160)
  doc.text("COMPARISON REPORT",h.W-14,16,{align:"right"})
  doc.text(date,h.W-14,24,{align:"right"})
  doc.text("generated by iGITit · OMARO PBC",h.W-14,32,{align:"right"})

  // Headline bar
  doc.setFillColor(...C.light); doc.rect(0,46,h.W,12,"F")
  doc.setDrawColor(...C.border); doc.setLineWidth(0.1)
  doc.line(0,46,h.W,46); doc.line(0,58,h.W,58)
  doc.setFontSize(8); doc.setFont("courier","normal"); doc.setTextColor(...C.subtext)
  const hlLines = doc.splitTextToSize(comparison.headline ?? `${nameA} vs ${nameB}`, h.W-28)
  doc.text(hlLines[0], 14, 54)

  // Repo name columns
  doc.setFillColor(...C.light); doc.rect(0,58,h.W,12,"F")
  doc.line(0,58,h.W,58); doc.line(0,70,h.W,70); doc.line(h.W/2,58,h.W/2,70)
  doc.setFontSize(9); doc.setFont("courier","bold"); doc.setTextColor(...C.text)
  doc.text(nameA, 14, 66)
  doc.text(nameB, h.W/2+4, 66)

  let y = 80

  // ── COMPARISON SECTIONS ───────────────────────────────
  for (const section of comparison.sections ?? []) {
    y = h.checkPage(y, 32)
    h.sectionLabel(y, section.title.toUpperCase()); y += 8
    const linesA = doc.splitTextToSize(section.leftSummary ?? "", colW - 8)
    const linesB = doc.splitTextToSize(section.rightSummary ?? "", colW - 8)
    doc.setFontSize(7.5); doc.setFont("courier","normal"); doc.setTextColor(...C.subtext)
    doc.text(linesA, 14, y)
    doc.text(linesB, h.W/2+6, y)
    const rowH = Math.max(linesA.length, linesB.length) * 4.5 + 4
    doc.setDrawColor(...C.border); doc.setLineWidth(0.1)
    doc.line(h.W/2, y-4, h.W/2, y+rowH)
    y += rowH
    // Verdict strip
    if (section.verdict) {
      doc.setFontSize(7); doc.setFont("courier","normal"); doc.setTextColor(...C.muted)
      const vLines = doc.splitTextToSize(`VERDICT  ${section.verdict}`, h.W - 32)
      const vBoxH = vLines.length * 4.5 + 6
      doc.setFillColor(...C.light); doc.rect(14, y, h.W-28, vBoxH, "F")
      doc.text(vLines, 18, y+5)
      y += vBoxH + 4
    }
    h.divider(y); y += 7
  }

  // ── KEY DIFFERENCES ───────────────────────────────────
  if (comparison.keyDifferences?.length > 0) {
    y = h.checkPage(y, 20)
    h.sectionLabel(y, "KEY DIFFERENCES"); y += 8
    for (const diff of comparison.keyDifferences) {
      y = h.checkPage(y, 10)
      doc.setFillColor(...C.blue); doc.circle(17, y-1.5, 1.5, "F")
      const lines = doc.splitTextToSize(diff, h.TEXT_W-10)
      doc.setFontSize(8); doc.setFont("courier","normal"); doc.setTextColor(...C.subtext)
      doc.text(lines, 22, y); y += lines.length * 4.5 + 4
    }
    h.divider(y); y += 7
  }

  // ── OVERALL WINNER ────────────────────────────────────
  y = h.checkPage(y, 35)
  h.sectionLabel(y, "OVERALL VERDICT"); y += 8
  const winnerText = `${comparison.overallWinner?.label ?? ""}\n\n${comparison.overallWinner?.reasoning ?? ""}`
  const boxH = h.verdictBox(y, winnerText)
  y += boxH + 8

  // ── FOR JOURNALISTS ───────────────────────────────────
  if (comparison.forJournalists) {
    y = h.checkPage(y, 20)
    h.sectionLabel(y, "FOR JOURNALISTS"); y += 8
    y += h.bodyText(14, y, comparison.forJournalists, h.TEXT_W) + 8
  }

  // ── INDIVIDUAL ANALYSES ───────────────────────────────
  // Shared helper — renders a full repo breakdown onto subsequent pages
  const writeFullRepo = (analysis: Analysis, label: string) => {
    doc.addPage(); h.footer()
    // Repo label banner
    doc.setFillColor(...C.black); doc.rect(0,0,h.W,46,"F")
    doc.setFillColor(...C.blue); doc.circle(17,22,3,"F")
    doc.setFontSize(14); doc.setFont("courier","bold"); doc.setTextColor(...C.white)
    doc.text(label, 27, 27)
    doc.setFontSize(8); doc.setFont("courier","normal"); doc.setTextColor(140,140,140)
    doc.text("full analysis", 27, 36)
    h.footer()
    let ry = 56

    // OVERVIEW
    h.sectionLabel(ry, "OVERVIEW"); ry += 8
    for (const section of analysis.overview ?? []) {
      ry = h.checkPage(ry, 22)
      h.sectionTitle(ry, section.title.toUpperCase()); ry += 6
      ry += h.bodyText(14, ry, section.content, h.TEXT_W); ry += 5
    }
    h.divider(ry); ry += 7

    // DATA NARRATIVE
    ry = h.checkPage(ry, 20)
    h.sectionLabel(ry, "DATA NARRATIVE"); ry += 8
    for (const item of analysis.dataItems ?? []) {
      ry = h.checkPage(ry, 16)
      const dotColor = item.type === "collect" ? C.blue : item.type === "store" ? C.green : C.red
      doc.setFillColor(...dotColor); doc.circle(17, ry-1.5, 2, "F")
      doc.setFontSize(9); doc.setFont("courier","bold"); doc.setTextColor(...C.text)
      doc.text(item.label, 22, ry)
      const descLines = doc.splitTextToSize(item.description, h.TEXT_W - 10)
      doc.setFontSize(8); doc.setFont("courier","normal"); doc.setTextColor(...C.subtext)
      doc.text(descLines, 22, ry+5)
      ry += 5 + descLines.length * 4.5 + 3
    }
    if (analysis.dataFlowSummary) {
      ry = h.checkPage(ry, 16)
      const sumLines = doc.splitTextToSize(analysis.dataFlowSummary, h.TEXT_W)
      doc.setFontSize(8); doc.setFont("courier","normal"); doc.setTextColor(...C.muted)
      doc.text(sumLines, 14, ry)
      ry += sumLines.length * 4.5 + 4
    }
    // Legend
    const legendItems = [
      { color: C.blue, label: "collected" },
      { color: C.green, label: "stored" },
      { color: C.red, label: "transmitted" },
    ]
    let lx = 14
    for (const li of legendItems) {
      doc.setFillColor(...li.color); doc.circle(lx+2, ry-1.5, 1.5, "F")
      doc.setFontSize(7); doc.setFont("courier","normal"); doc.setTextColor(...C.muted)
      doc.text(li.label, lx+6, ry)
      lx += doc.getTextWidth(li.label) + 14
    }
    ry += 5
    h.divider(ry); ry += 7

    // RESCUE SCORE
    ry = h.checkPage(ry, 20)
    const wrPillars = [
      { key: "R", label: "Resilience & Dependency Prevention" },
      { key: "E", label: "Equality / Non-Discrimination" },
      { key: "S", label: "Safety & Robustness" },
      { key: "C", label: "Control & Human Oversight" },
      { key: "U", label: "Use Limits & Proportionality" },
      { key: "E2", label: "Empowerment & Rights" },
      { key: "A", label: "Accountability & Privacy" },
      { key: "I", label: "Integrity & Transparency" },
    ]
    const wrScore = analysis.rescue
    const wrTotal = wrScore ? Object.values(wrScore).reduce((s, p) => s + (p as RescuePillar).score, 0) : 0
    const wrGrade = wrTotal >= 36 ? "A" : wrTotal >= 30 ? "B" : wrTotal >= 24 ? "C" : wrTotal >= 16 ? "D" : "F"
    h.sectionLabel(ry, `RESCUE SCORE · [${wrGrade}] ${wrTotal}/40 · GOVERNED BY OMARO PBC`); ry += 8
    if (wrScore) {
      for (const { key, label } of wrPillars) {
        ry = h.checkPage(ry, 12)
        const pillar = wrScore[key as keyof RescueScore]
        const pct = (pillar.score / 5) * 55
        const col = pillar.score >= 4 ? C.green : pillar.score >= 3 ? C.blue : pillar.score >= 2 ? C.amber : C.red
        doc.setFontSize(8); doc.setFont("courier","normal"); doc.setTextColor(...C.subtext)
        doc.text(`[${key}] ${label}`, 14, ry)
        doc.setFillColor(...C.border); doc.rect(100, ry-4, 55, 3, "F")
        doc.setFillColor(...col); doc.rect(100, ry-4, pct, 3, "F")
        doc.setFontSize(8); doc.setTextColor(...col)
        doc.text(`${pillar.score}/5`, h.W-14, ry, {align:"right"})
        const findLines = doc.splitTextToSize(pillar.finding, h.TEXT_W - 10)
        doc.setFontSize(7); doc.setTextColor(...C.muted)
        doc.text(findLines[0], 14, ry+4)
        ry += 12
      }
    }
    h.divider(ry); ry += 7

    // OVERALL VERDICT
    ry = h.checkPage(ry, 35)
    h.sectionLabel(ry, "OVERALL VERDICT"); ry += 8
    if (analysis.overallVerdict) {
      const bh = h.verdictBox(ry, analysis.overallVerdict)
      ry += bh + 8
    }

    // MODULES
    if (analysis.modules?.length > 0) {
      ry = h.checkPage(ry, 24)
      h.sectionLabel(ry, "MODULE BREAKDOWN"); ry += 8
      for (const mod of analysis.modules) {
        ry = h.checkPage(ry, 24)
        h.sectionTitle(ry, `${mod.name}  ·  ${mod.path}`); ry += 6
        ry += h.bodyText(14, ry, mod.description, h.TEXT_W); ry += 3
        h.divider(ry); ry += 7
      }
    }
  }

  writeFullRepo(analysisA, `REPO A: ${nameA}`)
  writeFullRepo(analysisB, `REPO B: ${nameB}`)

  doc.save(`igitit-compare-${metaA.repo}-vs-${metaB.repo}-${Date.now()}.pdf`)
}
