"use client"

import { useState, useRef, useCallback, useEffect } from "react"

// ─────────────────────────────────────────────
// TYPES
// ─────────────────────────────────────────────

type Tab = "overview" | "data" | "modules" | "score" | "changelog"

interface RepoMeta {
  owner: string
  repo: string
  description: string
  language: string
  stars: number
  fileCount: number
  license?: string | null
  topics?: string[]
  updatedAt?: string | null
  platform?: string
}

interface OverviewSection {
  title: string
  content: string
}

interface DataItem {
  type: "collect" | "store" | "send"
  label: string
  description: string
  sourceLine?: string
}

interface Module {
  name: string
  path: string
  description: string
  sourceSnippet?: string
}

interface ScoreDimension {
  label: string
  verdictLabel: string
  pass: boolean
  reasoning?: string
}

interface Analysis {
  meta: RepoMeta
  overview: OverviewSection[]
  dataItems: DataItem[]
  dataFlowSummary: string
  modules: Module[]
  score: ScoreDimension[]
  overallVerdict: string
}

interface HistoryEntry {
  id: string
  url: string
  label: string
  platform: "github" | "gitlab"
  analyzedAt: Date
  analysis: Analysis
}

interface ChangelogEntry {
  sha: string
  date: string
  author: string
  originalMessage: string
  plainTitle: string
  plainSummary: string
  significance: "routine" | "notable" | "flagged"
  significanceReason: string
  affectedAreas: string[]
}

// ─────────────────────────────────────────────
// BINARY ANIMATION HOOK
// ─────────────────────────────────────────────

function useBinaryAnimation() {
  const animate = useCallback((
    target: string,
    onUpdate: (val: string) => void,
    onDone: () => void
  ) => {
    const chars = "01"
    const duration = 800
    const steps = 12
    const interval = duration / steps
    let step = 0
    const tick = setInterval(() => {
      step++
      if (step >= steps) {
        clearInterval(tick)
        onUpdate(target)
        onDone()
        return
      }
      const progress = step / steps
      const resolved = Math.floor(progress * target.length)
      const animated = target
        .split("")
        .map((char, i) => {
          if (i < resolved) return char
          if (char === " ") return " "
          return chars[Math.floor(Math.random() * chars.length)]
        })
        .join("")
      onUpdate(animated)
    }, interval)
  }, [])
  return animate
}

// ─────────────────────────────────────────────
// HELPERS
// ─────────────────────────────────────────────

function detectPlatform(url: string): "github" | "gitlab" | null {
  if (url.includes("github.com")) return "github"
  if (url.includes("gitlab.com")) return "gitlab"
  return null
}

function repoLabelFromUrl(url: string): string {
  const match = url.match(/(?:github|gitlab)\.com\/([^/]+)\/([^/?\s#]+)/)
  if (match) return `${match[1]}/${match[2].replace(/\.git$/, "")}`
  return url
}

function formatDate(iso: string): string {
  try {
    return new Date(iso).toLocaleDateString("en-US", { year: "numeric", month: "short", day: "numeric" })
  } catch { return iso }
}

function buildTextReport(analysis: Analysis): string {
  const { meta, overview, dataItems, dataFlowSummary, modules, score, overallVerdict } = analysis
  const lines: string[] = []
  lines.push(`iGITit ANALYSIS REPORT`)
  lines.push(`Generated by iGITit · powered by Claude · an OMARO PBC product`)
  lines.push(`Repository: ${meta.owner}/${meta.repo}`)
  lines.push(`Platform: ${meta.platform ?? "GitHub"} · Language: ${meta.language} · Stars: ${meta.stars} · Files: ${meta.fileCount}`)
  if (meta.license) lines.push(`License: ${meta.license}`)
  lines.push(`Analyzed: ${new Date().toUTCString()}`)
  lines.push("")
  lines.push("═══════════════════════════════")
  lines.push("OVERVIEW")
  lines.push("═══════════════════════════════")
  for (const s of overview) {
    lines.push(""); lines.push(s.title); lines.push(s.content)
  }
  lines.push("")
  lines.push("═══════════════════════════════")
  lines.push("DATA NARRATIVE")
  lines.push("═══════════════════════════════")
  for (const item of dataItems) {
    const typeLabel = item.type === "collect" ? "[COLLECTED]" : item.type === "store" ? "[STORED]" : "[TRANSMITTED]"
    lines.push(`\n${typeLabel} ${item.label}`)
    lines.push(`  ${item.description}`)
    if (item.sourceLine) lines.push(`  Source: ${item.sourceLine}`)
  }
  lines.push(""); lines.push("DATA FLOW SUMMARY"); lines.push(dataFlowSummary)
  lines.push("")
  lines.push("═══════════════════════════════")
  lines.push("MODULE BREAKDOWN")
  lines.push("═══════════════════════════════")
  for (const mod of modules) {
    lines.push(`\n${mod.name}${mod.path ? ` (${mod.path})` : ""}`); lines.push(mod.description)
  }
  lines.push("")
  lines.push("═══════════════════════════════")
  lines.push("ACCOUNTABILITY SCORE")
  lines.push("═══════════════════════════════")
  for (const dim of score) {
    lines.push(`\n${dim.label}: ${dim.verdictLabel}`)
    if (dim.reasoning) lines.push(`  ${dim.reasoning}`)
  }
  lines.push(""); lines.push("OVERALL VERDICT"); lines.push(overallVerdict)
  lines.push("")
  lines.push("─────────────────────────────────────────────────────")
  lines.push("analysis reflects repository state at time of request · not legal or compliance advice")
  lines.push("igitit.xyz · omaro-pbc.org")
  return lines.join("\n")
}

// ─────────────────────────────────────────────
// SIGNIFICANCE CONFIG
// ─────────────────────────────────────────────

const SIG = {
  routine: { color: "rgba(255,255,255,0.25)", label: "routine", dot: "rgba(255,255,255,0.2)" },
  notable: { color: "#C4974A", label: "notable", dot: "#C4974A" },
  flagged: { color: "#E05C5C", label: "flagged", dot: "#E05C5C" },
}

// ─────────────────────────────────────────────
// MAIN PAGE
// ─────────────────────────────────────────────

export default function IGititPage() {
  const [url, setUrl] = useState("")
  const [isAnimating, setIsAnimating] = useState(false)
  const [isAnalyzing, setIsAnalyzing] = useState(false)
  const [analyzeStep, setAnalyzeStep] = useState(0)
  const [analysis, setAnalysis] = useState<Analysis | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [activeTab, setActiveTab] = useState<Tab>("overview")
  const [expandedModule, setExpandedModule] = useState<string | null>(null)
  const [history, setHistory] = useState<HistoryEntry[]>([])
  const [showHistory, setShowHistory] = useState(false)
  const [copyState, setCopyState] = useState<"idle" | "link" | "report">("idle")

  // Changelog state
  const [changelog, setChangelog] = useState<ChangelogEntry[] | null>(null)
  const [changelogLoading, setChangelogLoading] = useState(false)
  const [changelogError, setChangelogError] = useState<string | null>(null)
  const [changelogDepth, setChangelogDepth] = useState<10 | 25 | 50>(10)
  const [expandedCommit, setExpandedCommit] = useState<string | null>(null)

  const inputRef = useRef<HTMLInputElement>(null)
  const animateBinary = useBinaryAnimation()

  useEffect(() => {
    const params = new URLSearchParams(window.location.search)
    const repoParam = params.get("repo")
    if (repoParam) setUrl(decodeURIComponent(repoParam))
  }, [])

  const handleUrlChange = (val: string) => {
    setUrl(val)
    if (!val) return
    setIsAnimating(true)
    animateBinary(val, () => {}, () => setIsAnimating(false))
  }

  const handleAnalyze = async () => {
    if (!url.trim() || isAnalyzing) return
    const platform = detectPlatform(url.trim())
    if (!platform) {
      setError("Only GitHub (github.com) and GitLab (gitlab.com) URLs are supported.")
      return
    }

    setIsAnalyzing(true)
    setAnalysis(null)
    setError(null)
    setActiveTab("overview")
    setAnalyzeStep(0)
    setChangelog(null)
    setChangelogError(null)

    const params = new URLSearchParams()
    params.set("repo", encodeURIComponent(url.trim()))
    window.history.replaceState(null, "", `?${params.toString()}`)

    try {
      setAnalyzeStep(1)
      const repoRes = await fetch("/api/repo", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ url: url.trim() }),
      })
      if (!repoRes.ok) {
        const err = await repoRes.json()
        throw new Error(err.error ?? "Failed to fetch repository")
      }
      const repoData = await repoRes.json()

      setAnalyzeStep(2)
      const analyzeRes = await fetch("/api/analyze", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ ...repoData, meta: { ...repoData.meta, platform: platform === "github" ? "GitHub" : "GitLab" } }),
      })
      if (!analyzeRes.ok) {
        const err = await analyzeRes.json()
        throw new Error(err.error ?? "Failed to analyze repository")
      }
      const { analysis: analysisData, meta } = await analyzeRes.json()
      const fullAnalysis: Analysis = { ...analysisData, meta: { ...meta, platform: platform === "github" ? "GitHub" : "GitLab" } }

      setAnalysis(fullAnalysis)
      const entry: HistoryEntry = {
        id: crypto.randomUUID(),
        url: url.trim(),
        label: repoLabelFromUrl(url.trim()),
        platform,
        analyzedAt: new Date(),
        analysis: fullAnalysis,
      }
      setHistory(prev => [entry, ...prev.filter(h => h.label !== entry.label)].slice(0, 10))
    } catch (err) {
      setError(err instanceof Error ? err.message : "Something went wrong")
    } finally {
      setIsAnalyzing(false)
      setAnalyzeStep(0)
    }
  }

  const loadChangelog = async (depth: 10 | 25 | 50) => {
    if (!analysis) return
    setChangelogLoading(true)
    setChangelogError(null)
    setChangelog(null)
    setChangelogDepth(depth)
    try {
      const res = await fetch("/api/changelog", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          owner: analysis.meta.owner,
          repo: analysis.meta.repo,
          platform: analysis.meta.platform ?? "GitHub",
          depth,
        }),
      })
      if (!res.ok) {
        const err = await res.json()
        throw new Error(err.error ?? "Failed to fetch changelog")
      }
      const data = await res.json()
      setChangelog(data.changelog)
    } catch (err) {
      setChangelogError(err instanceof Error ? err.message : "Something went wrong")
    } finally {
      setChangelogLoading(false)
    }
  }

  const handleTabClick = (tab: Tab) => {
    setActiveTab(tab)
    if (tab === "changelog" && !changelog && !changelogLoading) {
      loadChangelog(changelogDepth)
    }
  }

  const handleCopyLink = async () => {
    await navigator.clipboard.writeText(window.location.href)
    setCopyState("link")
    setTimeout(() => setCopyState("idle"), 2000)
  }

  const handleCopyReport = async () => {
    if (!analysis) return
    await navigator.clipboard.writeText(buildTextReport(analysis))
    setCopyState("report")
    setTimeout(() => setCopyState("idle"), 2000)
  }

  const handleDownloadReport = () => {
    if (!analysis) return
    const text = buildTextReport(analysis)
    const blob = new Blob([text], { type: "text/plain" })
    const a = document.createElement("a")
    a.href = URL.createObjectURL(blob)
    a.download = `igitit-${analysis.meta.owner}-${analysis.meta.repo}-${Date.now()}.txt`
    a.click()
    URL.revokeObjectURL(a.href)
  }

  const dataColor = (type: "collect" | "store" | "send") => {
    if (type === "collect") return "#C4974A"
    if (type === "store") return "#4CAF7D"
    return "#E05C5C"
  }

  const scoreColor = (pass: boolean) => pass ? "#4CAF7D" : "#E05C5C"

  const STEPS = [
    "fetching repository tree…",
    "reading file structure…",
    "analyzing with Claude…",
    "generating plain-language output…",
  ]

  return (
    <div style={{
      minHeight: "100dvh",
      background: "#0b0b0c",
      fontFamily: "'IBM Plex Mono', 'Courier New', monospace",
      fontSize: "14px",
      color: "rgba(255,255,255,0.92)",
      padding: "48px 40px 120px",
      maxWidth: "1100px",
      margin: "0 auto",
    }}>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@300;400;500&display=swap');
        * { box-sizing: border-box; }
        ::selection { background: rgba(196,151,74,0.3); }
        ::-webkit-scrollbar { width: 4px; }
        ::-webkit-scrollbar-track { background: transparent; }
        ::-webkit-scrollbar-thumb { background: rgba(255,255,255,0.1); border-radius: 2px; }
        @keyframes blink { 0%,100%{opacity:1} 50%{opacity:0} }
        @keyframes fadeIn { from{opacity:0;transform:translateY(8px)} to{opacity:1;transform:translateY(0)} }
        @keyframes pulse { 0%,100%{opacity:0.5} 50%{opacity:1} }
        .tab-btn:hover { background: rgba(255,255,255,0.05) !important; }
        .module-card:hover { border-color: rgba(255,255,255,0.15) !important; }
        .analyze-btn:hover:not(:disabled) { background: rgba(196,151,74,0.9) !important; }
        .history-item:hover { background: rgba(255,255,255,0.05) !important; }
        .export-btn:hover { background: rgba(255,255,255,0.08) !important; border-color: rgba(255,255,255,0.2) !important; }
        .commit-card:hover { border-color: rgba(255,255,255,0.14) !important; }
        .depth-btn:hover { background: rgba(255,255,255,0.08) !important; }
      `}</style>

      {/* HEADER */}
      <div style={{
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        marginBottom: "40px",
        paddingBottom: "20px",
        borderBottom: "1px solid rgba(255,255,255,0.07)",
      }}>
        <div style={{ display: "flex", alignItems: "baseline", gap: "16px" }}>
          <div
            style={{ fontSize: "36px", letterSpacing: "-0.5px", cursor: "pointer" }}
            onClick={() => {
              setAnalysis(null); setError(null); setUrl(""); setChangelog(null)
              window.history.replaceState(null, "", window.location.pathname)
            }}
          >
            <span style={{ fontWeight: 500 }}>iGIT</span>
            <span style={{ fontWeight: 300, opacity: 0.7 }}>it</span>
          </div>
          <div style={{ fontSize: "18px", color: "rgba(255,255,255,0.4)", letterSpacing: "0.08em" }}>
            open source, open language.
          </div>
        </div>
        <div style={{ display: "flex", gap: "10px", alignItems: "center" }}>
          {history.length > 0 && (
            <button
              onClick={() => setShowHistory(!showHistory)}
              style={{
                fontSize: "13px",
                color: showHistory ? "#C4974A" : "rgba(255,255,255,0.4)",
                letterSpacing: "0.08em",
                border: `1px solid ${showHistory ? "rgba(196,151,74,0.4)" : "rgba(255,255,255,0.1)"}`,
                padding: "6px 14px",
                borderRadius: "4px",
                background: "transparent",
                fontFamily: "inherit",
                cursor: "pointer",
                transition: "all 0.15s",
              }}
            >
              [ history · {history.length} ]
            </button>
          )}
          <div style={{
            fontSize: "14px",
            color: "rgba(255,255,255,0.4)",
            letterSpacing: "0.1em",
            border: "1px solid rgba(255,255,255,0.1)",
            padding: "6px 20px",
            borderRadius: "4px",
          }}>
            OMARO PBC
          </div>
        </div>
      </div>

      {/* HISTORY PANEL */}
      {showHistory && history.length > 0 && (
        <div style={{
          marginBottom: "24px",
          background: "rgba(255,255,255,0.02)",
          border: "1px solid rgba(255,255,255,0.08)",
          borderRadius: "8px",
          overflow: "hidden",
          animation: "fadeIn 0.2s ease",
        }}>
          <div style={{ padding: "12px 20px", borderBottom: "1px solid rgba(255,255,255,0.06)", fontSize: "11px", letterSpacing: "0.1em", color: "rgba(255,255,255,0.3)" }}>
            SESSION HISTORY
          </div>
          {history.map((entry) => (
            <div
              key={entry.id}
              className="history-item"
              onClick={() => {
                setAnalysis(entry.analysis)
                setUrl(entry.url)
                setShowHistory(false)
                setActiveTab("overview")
                setChangelog(null)
                setChangelogError(null)
                const params = new URLSearchParams()
                params.set("repo", encodeURIComponent(entry.url))
                window.history.replaceState(null, "", `?${params.toString()}`)
              }}
              style={{
                padding: "12px 20px",
                display: "flex",
                alignItems: "center",
                gap: "12px",
                cursor: "pointer",
                borderBottom: "1px solid rgba(255,255,255,0.04)",
                transition: "background 0.1s",
              }}
            >
              <span style={{ fontSize: "14px", opacity: 0.5 }}>{entry.platform === "github" ? "⌥" : "◈"}</span>
              <span style={{ fontSize: "15px", color: "rgba(255,255,255,0.75)", flex: 1 }}>{entry.label}</span>
              <span style={{ fontSize: "12px", color: "rgba(255,255,255,0.25)" }}>
                {entry.analyzedAt.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}
              </span>
            </div>
          ))}
        </div>
      )}

      {/* INPUT */}
      <div style={{ marginBottom: "32px" }}>
        <div style={{ fontSize: "18px", color: "rgba(255,255,255,0.35)", letterSpacing: "0.06em", marginBottom: "12px" }}>
          paste a github or gitlab repository url
        </div>
        <div style={{ display: "flex", gap: "10px" }}>
          <div style={{
            flex: 1,
            background: "rgba(255,255,255,0.03)",
            border: `1px solid ${isAnimating ? "rgba(196,151,74,0.4)" : "rgba(255,255,255,0.1)"}`,
            borderRadius: "6px",
            padding: "16px 24px",
            position: "relative",
            overflow: "hidden",
            transition: "border-color 0.2s",
          }}>
            <input
              ref={inputRef}
              type="text"
              value={url}
              onChange={(e) => handleUrlChange(e.target.value)}
              onKeyDown={(e) => e.key === "Enter" && handleAnalyze()}
              placeholder="https://github.com/owner/repository"
              style={{
                width: "100%",
                background: "transparent",
                border: "none",
                outline: "none",
                fontFamily: "inherit",
                fontSize: "18px",
                color: isAnimating ? "#C4974A" : "rgba(255,255,255,0.88)",
                letterSpacing: isAnimating ? "0.02em" : "normal",
                transition: "color 0.2s",
              }}
            />
            {isAnimating && (
              <div style={{
                position: "absolute", bottom: 0, left: 0, right: 0, height: "1px",
                background: "linear-gradient(90deg, transparent, #C4974A, transparent)",
                animation: "pulse 0.4s ease-in-out infinite",
              }} />
            )}
          </div>
          <button
            className="analyze-btn"
            onClick={handleAnalyze}
            disabled={!url.trim() || isAnalyzing}
            style={{
              padding: "16px 32px",
              background: url.trim() && !isAnalyzing ? "#C4974A" : "rgba(255,255,255,0.06)",
              border: "1px solid rgba(255,255,255,0.1)",
              borderRadius: "6px",
              fontFamily: "inherit",
              fontSize: "18px",
              color: url.trim() && !isAnalyzing ? "#0b0b0c" : "rgba(255,255,255,0.3)",
              cursor: url.trim() && !isAnalyzing ? "pointer" : "default",
              letterSpacing: "0.08em",
              whiteSpace: "nowrap",
              transition: "all 0.15s",
            }}
          >
            {isAnalyzing ? "[ analyzing… ]" : "[ analyze ]"}
          </button>
        </div>
        {url.trim() && !isAnalyzing && (
          <div style={{ marginTop: "8px", fontSize: "12px", color: detectPlatform(url.trim()) ? "#4CAF7D" : "#E05C5C", letterSpacing: "0.06em", opacity: 0.7 }}>
            {detectPlatform(url.trim()) === "github" && "✓ github.com detected"}
            {detectPlatform(url.trim()) === "gitlab" && "✓ gitlab.com detected"}
            {!detectPlatform(url.trim()) && "⚠ only github.com and gitlab.com are supported"}
          </div>
        )}
      </div>

      {/* ERROR */}
      {error && !isAnalyzing && (
        <div style={{
          padding: "16px 20px", background: "rgba(224,92,92,0.08)", border: "1px solid rgba(224,92,92,0.3)",
          borderRadius: "8px", fontSize: "14px", color: "#E05C5C", marginBottom: "24px", animation: "fadeIn 0.3s ease",
        }}>
          <span style={{ marginRight: "8px" }}>⚠</span>{error}
        </div>
      )}

      {/* ANALYZING STATE */}
      {isAnalyzing && (
        <div style={{ padding: "32px", background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.07)", borderRadius: "8px", animation: "fadeIn 0.3s ease" }}>
          {STEPS.map((msg, i) => (
            <div key={i} style={{
              fontSize: "14px",
              color: i < analyzeStep ? "rgba(255,255,255,0.25)" : i === analyzeStep ? "rgba(255,255,255,0.7)" : "rgba(255,255,255,0.2)",
              letterSpacing: "0.04em", marginBottom: "10px", display: "flex", alignItems: "center", gap: "10px",
              animation: `fadeIn 0.4s ease ${i * 0.2}s both`,
            }}>
              <span style={{ color: i < analyzeStep ? "#4CAF7D" : i === analyzeStep ? "#C4974A" : "rgba(255,255,255,0.15)", fontSize: "12px" }}>
                {i < analyzeStep ? "✓" : i === analyzeStep ? "→" : "·"}
              </span>
              {msg}
              {i === analyzeStep && <span style={{ animation: "blink 0.8s step-end infinite" }}>_</span>}
            </div>
          ))}
        </div>
      )}

      {/* RESULTS */}
      {analysis && !isAnalyzing && (
        <div style={{ animation: "fadeIn 0.4s ease" }}>

          {/* REPO META */}
          <div style={{ marginBottom: "24px" }}>
            <div style={{ display: "flex", alignItems: "flex-start", justifyContent: "space-between", marginBottom: "6px", flexWrap: "wrap", gap: "8px" }}>
              <div style={{ fontSize: "18px", fontWeight: 500, letterSpacing: "0.02em" }}>
                {analysis.meta.owner}/{analysis.meta.repo}
              </div>
              <div style={{ display: "flex", gap: "6px", flexWrap: "wrap" }}>
                {analysis.meta.platform && (
                  <span style={{ fontSize: "12px", padding: "3px 10px", border: "1px solid rgba(255,255,255,0.12)", borderRadius: "4px", color: "rgba(255,255,255,0.6)" }}>{analysis.meta.platform}</span>
                )}
                {analysis.meta.language && (
                  <span style={{ fontSize: "12px", padding: "3px 10px", border: "1px solid rgba(255,255,255,0.12)", borderRadius: "4px", color: "rgba(255,255,255,0.6)" }}>{analysis.meta.language}</span>
                )}
                <span style={{ fontSize: "12px", padding: "3px 10px", border: "1px solid rgba(255,255,255,0.12)", borderRadius: "4px", color: "rgba(255,255,255,0.6)" }}>★ {analysis.meta.stars}</span>
                <span style={{ fontSize: "12px", padding: "3px 10px", border: "1px solid rgba(255,255,255,0.12)", borderRadius: "4px", color: "rgba(255,255,255,0.6)" }}>{analysis.meta.fileCount} files</span>
                {analysis.meta.license && (
                  <span style={{ fontSize: "12px", padding: "3px 10px", border: "1px solid rgba(196,151,74,0.3)", borderRadius: "4px", color: "#C4974A" }}>{analysis.meta.license}</span>
                )}
              </div>
            </div>
            {analysis.meta.description && (
              <div style={{ fontSize: "14px", color: "rgba(255,255,255,0.4)", lineHeight: 1.6 }}>{analysis.meta.description}</div>
            )}
          </div>

          {/* EXPORT BAR */}
          <div style={{ display: "flex", gap: "8px", marginBottom: "20px", flexWrap: "wrap" }}>
            {[
              { id: "link", label: copyState === "link" ? "✓ link copied" : "[ copy link ]", action: handleCopyLink },
              { id: "report", label: copyState === "report" ? "✓ copied" : "[ copy report ]", action: handleCopyReport },
              { id: "download", label: "[ download .txt ]", action: handleDownloadReport },
            ].map((btn) => (
              <button key={btn.id} className="export-btn" onClick={btn.action} style={{
                padding: "8px 16px",
                background: "rgba(255,255,255,0.03)",
                border: "1px solid rgba(255,255,255,0.1)",
                borderRadius: "6px",
                fontFamily: "inherit",
                fontSize: "13px",
                color: (btn.id === "link" && copyState === "link") || (btn.id === "report" && copyState === "report") ? "#4CAF7D" : "rgba(255,255,255,0.4)",
                cursor: "pointer",
                letterSpacing: "0.06em",
                transition: "all 0.15s",
              }}>
                {btn.label}
              </button>
            ))}
          </div>

          {/* TABS — 5 columns */}
          <div style={{ display: "grid", gridTemplateColumns: "repeat(5, 1fr)", gap: "8px", marginBottom: "20px" }}>
            {([
              { id: "overview", label: "[ overview ]" },
              { id: "data", label: "[ data narrative ]" },
              { id: "modules", label: "[ module breakdown ]" },
              { id: "score", label: "[ score ]" },
              { id: "changelog", label: "[ change log ]" },
            ] as { id: Tab; label: string }[]).map((tab) => (
              <button
                key={tab.id}
                className="tab-btn"
                onClick={() => handleTabClick(tab.id)}
                style={{
                  padding: "14px 6px",
                  background: activeTab === tab.id ? "rgba(196,151,74,0.1)" : "rgba(255,255,255,0.03)",
                  border: `1px solid ${activeTab === tab.id ? "#C4974A" : "rgba(255,255,255,0.08)"}`,
                  borderRadius: "8px",
                  fontFamily: "inherit",
                  fontSize: "14px",
                  color: activeTab === tab.id ? "#C4974A" : "rgba(255,255,255,0.45)",
                  cursor: "pointer",
                  letterSpacing: "0.03em",
                  lineHeight: 1.4,
                  transition: "all 0.15s",
                  textAlign: "center",
                }}
              >
                {tab.label}
              </button>
            ))}
          </div>

          {/* TAB CONTENT */}
          <div key={activeTab} style={{ animation: "fadeIn 0.25s ease" }}>

            {/* OVERVIEW */}
            {activeTab === "overview" && (
              <div style={{ display: "flex", flexDirection: "column", gap: "12px" }}>
                {analysis.overview.map((section, i) => (
                  <div key={i} style={{ padding: "36px 40px", background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.07)", borderRadius: "8px" }}>
                    <div style={{ fontSize: "12px", letterSpacing: "0.12em", color: "rgba(255,255,255,0.3)", marginBottom: "16px" }}>{section.title}</div>
                    <div style={{ fontSize: "18px", lineHeight: 1.75, color: "rgba(255,255,255,0.82)", fontWeight: 300 }}>{section.content}</div>
                  </div>
                ))}
              </div>
            )}

            {/* DATA NARRATIVE */}
            {activeTab === "data" && (
              <div style={{ display: "flex", flexDirection: "column", gap: "12px" }}>
                <div style={{ padding: "36px 40px", background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.07)", borderRadius: "8px" }}>
                  <div style={{ fontSize: "12px", letterSpacing: "0.12em", color: "rgba(255,255,255,0.3)", marginBottom: "20px" }}>DATA THIS SOFTWARE TOUCHES</div>
                  <div style={{ display: "flex", flexDirection: "column", gap: "14px" }}>
                    {analysis.dataItems.map((item, i) => (
                      <div key={i} style={{ display: "flex", gap: "14px", alignItems: "flex-start" }}>
                        <div style={{ width: "8px", height: "8px", borderRadius: "50%", background: dataColor(item.type), flexShrink: 0, marginTop: "7px" }} />
                        <div>
                          <span style={{ fontSize: "18px", color: "rgba(255,255,255,0.82)", fontWeight: 400 }}>{item.label}</span>
                          <span style={{ fontSize: "18px", color: "rgba(255,255,255,0.4)", fontWeight: 300 }}>{" "}— {item.description}</span>
                          {item.sourceLine && (
                            <div style={{ marginTop: "4px", fontSize: "12px", color: "#C4974A", opacity: 0.7 }}>→ {item.sourceLine}</div>
                          )}
                        </div>
                      </div>
                    ))}
                  </div>
                  <div style={{ display: "flex", gap: "16px", marginTop: "24px", paddingTop: "20px", borderTop: "1px solid rgba(255,255,255,0.06)" }}>
                    {[{ color: "#C4974A", label: "collected" }, { color: "#4CAF7D", label: "stored" }, { color: "#E05C5C", label: "transmitted" }].map(({ color, label }) => (
                      <div key={label} style={{ display: "flex", alignItems: "center", gap: "6px" }}>
                        <div style={{ width: "7px", height: "7px", borderRadius: "50%", background: color }} />
                        <span style={{ fontSize: "12px", color: "rgba(255,255,255,0.35)", letterSpacing: "0.04em" }}>{label}</span>
                      </div>
                    ))}
                  </div>
                </div>
                <div style={{ padding: "36px 40px", background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.07)", borderRadius: "8px" }}>
                  <div style={{ fontSize: "12px", letterSpacing: "0.12em", color: "rgba(255,255,255,0.3)", marginBottom: "16px" }}>DATA FLOW SUMMARY</div>
                  <div style={{ fontSize: "18px", lineHeight: 1.75, color: "rgba(255,255,255,0.7)", fontWeight: 300 }}>{analysis.dataFlowSummary}</div>
                </div>
              </div>
            )}

            {/* MODULE BREAKDOWN */}
            {activeTab === "modules" && (
              <div style={{ display: "flex", flexDirection: "column", gap: "10px" }}>
                {analysis.modules.map((mod, i) => (
                  <div key={i} className="module-card" style={{ border: "1px solid rgba(255,255,255,0.08)", borderRadius: "8px", overflow: "hidden", transition: "border-color 0.15s" }}>
                    <div style={{ padding: "24px 32px", cursor: "pointer" }} onClick={() => setExpandedModule(expandedModule === mod.name ? null : mod.name)}>
                      <div style={{ display: "flex", alignItems: "flex-start", justifyContent: "space-between", marginBottom: "10px" }}>
                        <div style={{ fontSize: "16px", fontWeight: 500, color: "rgba(255,255,255,0.88)" }}>{mod.name}</div>
                        <div style={{ display: "flex", alignItems: "center", gap: "10px" }}>
                          {mod.path && (
                            <span style={{ fontSize: "11px", padding: "3px 8px", background: "rgba(255,255,255,0.05)", borderRadius: "4px", color: "rgba(255,255,255,0.35)", letterSpacing: "0.06em" }}>{mod.path}</span>
                          )}
                          {mod.sourceSnippet && (
                            <span style={{ fontSize: "13px", color: "rgba(255,255,255,0.25)" }}>{expandedModule === mod.name ? "▲" : "▼"}</span>
                          )}
                        </div>
                      </div>
                      <div style={{ fontSize: "18px", lineHeight: 1.75, color: "rgba(255,255,255,0.55)", fontWeight: 300 }}>{mod.description}</div>
                    </div>
                    {expandedModule === mod.name && mod.sourceSnippet && (
                      <div style={{ borderTop: "1px solid rgba(255,255,255,0.06)", background: "rgba(0,0,0,0.3)", animation: "fadeIn 0.2s ease" }}>
                        <div style={{ padding: "10px 32px", borderBottom: "1px solid rgba(255,255,255,0.05)", fontSize: "11px", color: "rgba(255,255,255,0.25)", letterSpacing: "0.1em", display: "flex", justifyContent: "space-between" }}>
                          <span>[ source ]</span><span>{mod.path}</span>
                        </div>
                        <pre style={{ padding: "20px 32px", margin: 0, fontSize: "13px", lineHeight: 1.7, overflowX: "auto", fontFamily: "inherit", whiteSpace: "pre-wrap" }}>
                          {mod.sourceSnippet.split("\n").map((line, li) => (
                            <span key={li} style={{ display: "block", color: line.trim().startsWith("//") ? "rgba(255,255,255,0.25)" : "rgba(255,255,255,0.65)" }}>{line}</span>
                          ))}
                        </pre>
                      </div>
                    )}
                  </div>
                ))}
              </div>
            )}

            {/* SCORE */}
            {activeTab === "score" && (
              <div style={{ display: "flex", flexDirection: "column", gap: "12px" }}>
                <div style={{ padding: "36px 40px", background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.07)", borderRadius: "8px" }}>
                  <div style={{ fontSize: "12px", letterSpacing: "0.12em", color: "rgba(255,255,255,0.3)", marginBottom: "24px" }}>
                    ACCOUNTABILITY SCORE · {analysis.meta.owner}/{analysis.meta.repo}
                  </div>
                  <div style={{ display: "flex", flexDirection: "column", gap: "24px" }}>
                    {analysis.score.map((dim, i) => (
                      <div key={i}>
                        <div style={{ display: "flex", justifyContent: "space-between", marginBottom: "8px" }}>
                          <span style={{ fontSize: "16px", color: "rgba(255,255,255,0.7)", fontWeight: 300 }}>{dim.label}</span>
                          <span style={{ fontSize: "14px", color: scoreColor(dim.pass), letterSpacing: "0.04em" }}>{dim.verdictLabel}</span>
                        </div>
                        <div style={{ height: "3px", background: "rgba(255,255,255,0.06)", borderRadius: "2px", overflow: "hidden", marginBottom: dim.reasoning ? "8px" : "0" }}>
                          <div style={{ height: "100%", width: dim.pass ? "85%" : "20%", background: scoreColor(dim.pass), borderRadius: "2px", transition: "width 0.6s ease" }} />
                        </div>
                        {dim.reasoning && (
                          <div style={{ fontSize: "13px", color: "rgba(255,255,255,0.3)", lineHeight: 1.6, fontStyle: "italic" }}>{dim.reasoning}</div>
                        )}
                      </div>
                    ))}
                  </div>
                </div>
                <div style={{ padding: "36px 40px", background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.07)", borderRadius: "8px" }}>
                  <div style={{ fontSize: "12px", letterSpacing: "0.12em", color: "rgba(255,255,255,0.3)", marginBottom: "16px" }}>OVERALL VERDICT</div>
                  <div style={{ fontSize: "18px", lineHeight: 1.75, color: "rgba(255,255,255,0.7)", fontWeight: 300 }}>{analysis.overallVerdict}</div>
                </div>
              </div>
            )}

            {/* CHANGE LOG */}
            {activeTab === "changelog" && (
              <div style={{ display: "flex", flexDirection: "column", gap: "12px" }}>

                {/* DEPTH SELECTOR */}
                <div style={{
                  display: "flex",
                  alignItems: "center",
                  gap: "10px",
                  padding: "16px 20px",
                  background: "rgba(255,255,255,0.02)",
                  border: "1px solid rgba(255,255,255,0.07)",
                  borderRadius: "8px",
                }}>
                  <span style={{ fontSize: "13px", color: "rgba(255,255,255,0.3)", letterSpacing: "0.06em", marginRight: "4px" }}>commits to analyze:</span>
                  {([10, 25, 50] as const).map((n) => (
                    <button
                      key={n}
                      className="depth-btn"
                      onClick={() => loadChangelog(n)}
                      disabled={changelogLoading}
                      style={{
                        padding: "6px 16px",
                        background: changelogDepth === n && changelog ? "rgba(196,151,74,0.15)" : "rgba(255,255,255,0.04)",
                        border: `1px solid ${changelogDepth === n && changelog ? "#C4974A" : "rgba(255,255,255,0.1)"}`,
                        borderRadius: "4px",
                        fontFamily: "inherit",
                        fontSize: "13px",
                        color: changelogDepth === n && changelog ? "#C4974A" : "rgba(255,255,255,0.4)",
                        cursor: changelogLoading ? "default" : "pointer",
                        letterSpacing: "0.06em",
                        transition: "all 0.15s",
                      }}
                    >
                      {n}
                    </button>
                  ))}
                  {changelog && !changelogLoading && (
                    <span style={{ fontSize: "12px", color: "rgba(255,255,255,0.2)", marginLeft: "auto" }}>
                      {changelog.filter(c => c.significance === "flagged").length} flagged · {changelog.filter(c => c.significance === "notable").length} notable · {changelog.filter(c => c.significance === "routine").length} routine
                    </span>
                  )}
                </div>

                {/* LOADING */}
                {changelogLoading && (
                  <div style={{ padding: "40px", textAlign: "center", color: "rgba(255,255,255,0.3)", fontSize: "14px", letterSpacing: "0.06em" }}>
                    <span style={{ animation: "blink 0.8s step-end infinite" }}>scanning commit history…_</span>
                  </div>
                )}

                {/* ERROR */}
                {changelogError && !changelogLoading && (
                  <div style={{ padding: "16px 20px", background: "rgba(224,92,92,0.08)", border: "1px solid rgba(224,92,92,0.3)", borderRadius: "8px", fontSize: "14px", color: "#E05C5C" }}>
                    <span style={{ marginRight: "8px" }}>⚠</span>{changelogError}
                  </div>
                )}

                {/* COMMIT TIMELINE */}
                {changelog && !changelogLoading && (
                  <div style={{ display: "flex", flexDirection: "column", gap: "8px" }}>
                    {changelog.map((commit, i) => {
                      const sig = SIG[commit.significance] ?? SIG.routine
                      const isExpanded = expandedCommit === commit.sha
                      return (
                        <div
                          key={i}
                          className="commit-card"
                          style={{
                            border: `1px solid ${commit.significance === "flagged" ? "rgba(224,92,92,0.25)" : commit.significance === "notable" ? "rgba(196,151,74,0.18)" : "rgba(255,255,255,0.07)"}`,
                            borderRadius: "8px",
                            overflow: "hidden",
                            background: commit.significance === "flagged" ? "rgba(224,92,92,0.04)" : "rgba(255,255,255,0.015)",
                            transition: "border-color 0.15s",
                          }}
                        >
                          <div
                            style={{ padding: "20px 28px", cursor: "pointer" }}
                            onClick={() => setExpandedCommit(isExpanded ? null : commit.sha)}
                          >
                            <div style={{ display: "flex", alignItems: "flex-start", gap: "14px" }}>
                              <div style={{ width: "8px", height: "8px", borderRadius: "50%", background: sig.dot, flexShrink: 0, marginTop: "6px" }} />
                              <div style={{ flex: 1, minWidth: 0 }}>
                                <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", gap: "12px", marginBottom: "6px" }}>
                                  <div style={{ fontSize: "15px", fontWeight: 500, color: "rgba(255,255,255,0.88)", lineHeight: 1.4 }}>
                                    {commit.plainTitle}
                                  </div>
                                  <div style={{ display: "flex", alignItems: "center", gap: "8px", flexShrink: 0 }}>
                                    <span style={{ fontSize: "11px", color: sig.color, letterSpacing: "0.08em", border: `1px solid ${sig.dot}`, padding: "2px 8px", borderRadius: "4px", opacity: 0.8 }}>
                                      {commit.significance}
                                    </span>
                                    <span style={{ fontSize: "11px", color: "rgba(255,255,255,0.2)" }}>{isExpanded ? "▲" : "▼"}</span>
                                  </div>
                                </div>
                                <div style={{ fontSize: "15px", lineHeight: 1.65, color: "rgba(255,255,255,0.45)", fontWeight: 300 }}>
                                  {commit.plainSummary}
                                </div>
                                <div style={{ display: "flex", alignItems: "center", gap: "12px", marginTop: "10px", flexWrap: "wrap" }}>
                                  <span style={{ fontSize: "11px", color: "rgba(255,255,255,0.2)", fontFamily: "inherit" }}>{commit.sha}</span>
                                  <span style={{ fontSize: "11px", color: "rgba(255,255,255,0.2)" }}>{formatDate(commit.date)}</span>
                                  <span style={{ fontSize: "11px", color: "rgba(255,255,255,0.2)" }}>{commit.author}</span>
                                  {commit.affectedAreas?.map((area, ai) => (
                                    <span key={ai} style={{ fontSize: "11px", padding: "2px 8px", background: "rgba(255,255,255,0.05)", borderRadius: "3px", color: "rgba(255,255,255,0.3)" }}>
                                      {area}
                                    </span>
                                  ))}
                                </div>
                              </div>
                            </div>
                          </div>

                          {/* EXPANDED */}
                          {isExpanded && (
                            <div style={{ borderTop: "1px solid rgba(255,255,255,0.06)", background: "rgba(0,0,0,0.2)", padding: "16px 28px 20px", animation: "fadeIn 0.2s ease" }}>
                              <div style={{ fontSize: "12px", color: "rgba(255,255,255,0.2)", letterSpacing: "0.08em", marginBottom: "8px" }}>ORIGINAL COMMIT MESSAGE</div>
                              <div style={{ fontSize: "13px", color: "rgba(255,255,255,0.4)", fontFamily: "inherit", marginBottom: "16px", lineHeight: 1.6 }}>
                                {commit.originalMessage}
                              </div>
                              {commit.significanceReason && (
                                <>
                                  <div style={{ fontSize: "12px", color: "rgba(255,255,255,0.2)", letterSpacing: "0.08em", marginBottom: "8px" }}>WHY {commit.significance.toUpperCase()}</div>
                                  <div style={{ fontSize: "13px", color: sig.color, opacity: 0.8, lineHeight: 1.6 }}>{commit.significanceReason}</div>
                                </>
                              )}
                            </div>
                          )}
                        </div>
                      )
                    })}
                  </div>
                )}
              </div>
            )}
          </div>

          {/* LISTEN BAR */}
          <div style={{
            marginTop: "24px", padding: "16px 20px", background: "rgba(255,255,255,0.02)",
            border: "1px solid rgba(255,255,255,0.07)", borderRadius: "8px", display: "flex", alignItems: "center", gap: "16px",
          }}>
            <span style={{ fontSize: "14px", color: "rgba(255,255,255,0.3)", letterSpacing: "0.06em", whiteSpace: "nowrap" }}>[ listen to analysis ]</span>
            <select style={{ flex: 1, background: "rgba(255,255,255,0.04)", border: "1px solid rgba(255,255,255,0.1)", borderRadius: "6px", padding: "8px 12px", fontFamily: "inherit", fontSize: "14px", color: "rgba(255,255,255,0.6)", outline: "none", cursor: "pointer" }}>
              <option value="overview">overview</option>
              <option value="data">data narrative</option>
              <option value="modules">module breakdown</option>
              <option value="score">accountability score</option>
            </select>
            <button style={{ width: "52px", height: "44px", borderRadius: "8px", background: "#C4974A", border: "none", fontFamily: "inherit", fontSize: "13px", color: "#0b0b0c", cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }}>▶</button>
          </div>
        </div>
      )}

      {/* FOOTER */}
      <div style={{
        marginTop: "60px", paddingTop: "20px", borderTop: "1px solid rgba(255,255,255,0.05)",
        fontSize: "14px", color: "rgba(255,255,255,0.2)", lineHeight: 1.7, letterSpacing: "0.04em",
      }}>
        <div>generated by iGITit · powered by Claude · an OMARO PBC product · igitit.xyz (coming soon)</div>
        <div>analysis reflects repository state at time of request · not legal or compliance advice</div>
      </div>
    </div>
  )
}
